using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace REALWorks.Asset.Api.Model
{
    public class Tenant:BaseModel
    {
        //[BsonId] // standard BSonId generated by MongoDb
        //public ObjectId Id { get; set; }

        public string ProoertyId { get; set; }

        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ContactTelephone { get; set; }
        public string ContactEmail { get; set; }
        public string OnlineLoginName { get; set; } // for future use to login to clinet portal        
        public bool isActive { get; set; }       

        public DateTime MoveInDate { get; set; }
        public DateTime MoveOutDate { get; set; }
        public DateTime RentalStartDate { get; set; }
        public DateTime RentalEndDate { get; set; }

        public string Notes { get; set; }

        public DateTime DateAdded { get; set; }
        public DateTime DateUpdated { get; set; }
    }
}
